Repository teslamate-org/teslamate, pull requests merged in 2024-06, with the labels that each got.

#3945 Update default.po for thai
  priv/gettext/th/LC_MESSAGES/default.po
Labels: enhancement

#3943 Respect Retry-After header on 429 response code
  .gitignore
  lib/tesla_api/vehicle.ex
  lib/teslamate/api.ex
  lib/teslamate/vehicles/vehicle.ex
  test/teslamate/api_test.exs
Labels: enhancement

#3895 Grafana 11.0.0
  grafana/Dockerfile
Labels: area:grafana, docker

#3886 [Docs] Add network flows that should be authorized
  website/docs/faq.md
Labels: enhancement

#3859 Projected Range fix (using usable_battery_level)
  grafana/dashboards/projected-range.json
Labels: area:dashboard

#3953 Update projects.md with new MMM
  website/docs/projects.md
Labels: kind:documentation

#3973 doc: fix MMM-Teslamate and ha-addon-teslamate project links
  website/docs/projects.md
Labels: kind:documentation

#3962 Track open/close states for individual doors
  lib/teslamate/mqtt/pubsub/vehicle_subscriber.ex
  lib/teslamate/vehicles/vehicle/summary.ex
  website/docs/integrations/mqtt.md
Labels: enhancement

#3984 Allow Fleet API users to change client_id
  lib/tesla_api/auth.ex
  website/docs/configuration/environment_variables.md
Labels: area:tesla api

#3867 Update drives.json: show drives with duration=0 but distance>0
  grafana/dashboards/drives.json
Labels: area:dashboard

#4017 doc: update the Contributor's Guide with the latest requirements
  CHANGELOG.md
  website/docs/development.md
Labels: kind:documentation
