Repository teslamate-org/teslamate, pull requests merged in 2024-02, with the labels that each got.

#3630 fix: use product api endpoint to fetch vehicles
  lib/tesla_api/vehicle.ex
Labels: WIP, area:tesla api

#3650 Add details how to configuring the TZ environment variable
  CHANGELOG.md
Labels: kind:documentation

#3566 Add Thai Translation
  priv/gettext/th/LC_MESSAGES/default.po
  priv/gettext/th/LC_MESSAGES/errors.po
Labels: enhancement, note:needs investigation, area:teslamate

#3656 doc: add instructions, how to connect to database before editing cars
  website/docs/maintenance/manually_fixing_data.mdx
Labels: kind:documentation

#3615 Upgrade to Phoenix 1.7
  .formatter.exs
  lib/teslamate_web.ex
  lib/teslamate_web/endpoint.ex
  lib/teslamate_web/live/car_live/index.html.heex
  lib/teslamate_web/live/car_live/summary.html.heex
  lib/teslamate_web/live/charge_live/cost.html.heex
  lib/teslamate_web/live/geofence_live/form.html.heex
  lib/teslamate_web/live/geofence_live/index.html.heex
  lib/teslamate_web/live/import_live/index.html.heex
  lib/teslamate_web/live/init_assigns.ex
  lib/teslamate_web/live/settings_live/index.html.heex
  lib/teslamate_web/live/signin_live/index.html.heex
  lib/teslamate_web/router.ex
  lib/teslamate_web/templates/layout/root.html.heex
  mix.exs
  mix.lock
  priv/gettext/da/LC_MESSAGES/default.po
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/en/LC_MESSAGES/default.po
  priv/gettext/es/LC_MESSAGES/default.po
  priv/gettext/fi/LC_MESSAGES/default.po
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/gettext/ja/LC_MESSAGES/default.po
  priv/gettext/ko/LC_MESSAGES/default.po
  priv/gettext/nb/LC_MESSAGES/default.po
  priv/gettext/nl/LC_MESSAGES/default.po
  priv/gettext/sv/LC_MESSAGES/default.po
  priv/gettext/tr/LC_MESSAGES/default.po
  priv/gettext/uk/LC_MESSAGES/default.po
  priv/gettext/zh_Hans/LC_MESSAGES/default.po
  priv/gettext/zh_Hant/LC_MESSAGES/default.po
  test/support/conn_case.ex
  test/teslamate_web/controllers/car_controller_test.exs
  test/teslamate_web/live/car_summary_live_test.exs
  test/teslamate_web/live/charge_cost_live_test.exs
  test/teslamate_web/live/geofence_live_test.exs
  test/teslamate_web/live/settings_test.exs
Labels: note:needs investigation, area:teslamate

#3662 feat: add missing message translation for French
  priv/gettext/fr/LC_MESSAGES/default.po
Labels: enhancement

#3667 Add stat panel for selected duration in drive details dashboard
  grafana/dashboards/internal/drive-details.json
Labels: enhancement, area:grafana

#3694 Add missing German translation, fix mistakes
  priv/gettext/de/LC_MESSAGES/default.po
Labels: enhancement

#3693 feat: add missing translation for Korean
  priv/gettext/ko/LC_MESSAGES/default.po
Labels: enhancement

#3699 Update default.po
  priv/gettext/zh_Hant/LC_MESSAGES/default.po
Labels: enhancement
