Repository teslamate-org/teslamate, pull requests merged in 2025-05, with the labels that each got.

#4723 fix(nix): update cldr hash
  CHANGELOG.md
  nix/flake-modules/package.nix
Labels: enhancement

#4721 feat: use Grafana 12.0.0
  CHANGELOG.md
  grafana/Dockerfile
  grafana/dashboards/battery-health.json
  grafana/dashboards/charge-level.json
  grafana/dashboards/charges.json
  grafana/dashboards/charging-stats.json
  grafana/dashboards/database-info.json
  grafana/dashboards/drive-stats.json
  grafana/dashboards/drives.json
  grafana/dashboards/efficiency.json
  grafana/dashboards/internal/charge-details.json
  grafana/dashboards/internal/drive-details.json
  grafana/dashboards/internal/home.json
  grafana/dashboards/locations.json
  grafana/dashboards/mileage.json
  grafana/dashboards/overview.json
  grafana/dashboards/projected-range.json
  grafana/dashboards/reports/dutch-tax.json
  grafana/dashboards/states.json
  grafana/dashboards/statistics.json
  grafana/dashboards/timeline.json
  grafana/dashboards/trip.json
  grafana/dashboards/updates.json
  grafana/dashboards/vampire-drain.json
  grafana/dashboards/visited.json
  nix/module.nix
Labels: area:grafana, docker

#4742 feat: update image on home dashboard to juniper and back to dark
  grafana/dashboards/internal/home.json
Labels: area:dashboard

#4734 docs: improvement to the Debian installation instructions
  CHANGELOG.md
  website/docs/installation/debian.md
Labels: kind:documentation

#4737 docs: add note on accessory power functionality can prevent car sleep
  website/docs/faq.md
Labels: kind:documentation

#4746 fix: consumption for drives with positive soc diff
  CHANGELOG.md
  grafana/dashboards/drive-stats.json
  grafana/dashboards/drives.json
  grafana/dashboards/internal/drive-details.json
  grafana/dashboards/overview.json
  grafana/dashboards/statistics.json
  grafana/dashboards/trip.json
Labels: area:dashboard

#4715 feat: preserve the folders when restoring dashboards
  grafana/dashboards.sh
Labels: area:grafana

#4748 i18n: more descriptive italian localization
  priv/gettext/it/LC_MESSAGES/default.po
Labels: enhancement

#4763 fix(nix): skip duplicate cldr download to fix build on darwin and improve reproducibility
  CHANGELOG.md
  nix/flake-modules/package.nix
Labels: kind:bug
