Repository teslamate-org/teslamate, pull requests merged in 2025-01, with the labels that each got.

#4463 replace cross join with left join
  grafana/dashboards/battery-health.json
Labels: area:dashboard

#4466 doc: added missing topic "charging_state" in mqtt doc
  website/docs/integrations/mqtt.md
Labels: kind:documentation

#4474 docs: Grafana 11.4 for manual install on FreeBSD
  website/docs/installation/freebsd.md
Labels: kind:documentation

#4470 doc: Fixing typo for sensor psi calculation
  website/docs/integrations/home_assistant.md
Labels: kind:documentation

#4472 doc: Simplify Home Assistant sensors, add device_class to allow changing measurement units
  website/docs/integrations/home_assistant.md
Labels: kind:documentation

#4473 feat: optimize state transitions
  lib/teslamate/vehicles/vehicle.ex
Labels: enhancement, area:teslamate

#4498 feat: add 0 as lower bound for gauge to ensure proper scaling
  grafana/dashboards/drives.json
  grafana/dashboards/efficiency.json
  grafana/dashboards/statistics.json
Labels: area:dashboard
