Repository teslamate-org/teslamate, pull requests merged in 2025-03, with the labels that each got.

#4574 docs: Update REINDEX notes
  website/docs/maintenance/manually_fixing_data.mdx
Labels: kind:documentation

#4578 feat: add Database Information Dashboard
  grafana/dashboards/database-info.json
  website/docs/screenshots.mdx
  website/static/screenshots/db-info.png
Labels: enhancement, area:dashboard

#4577 fix: update mix dependency hash in nix builds.
  nix/flake-modules/package.nix
Labels: dependencies

#4573 docs: Update projects using TeslaMate
  website/docs/projects.md
Labels: kind:documentation

#4570 feat: Grafana 11.6.0
  grafana/Dockerfile
  grafana/dashboards/battery-health.json
  grafana/dashboards/charge-level.json
  grafana/dashboards/charges.json
  grafana/dashboards/charging-stats.json
  grafana/dashboards/database-info.json
  grafana/dashboards/drive-stats.json
  grafana/dashboards/drives.json
  grafana/dashboards/efficiency.json
  grafana/dashboards/internal/charge-details.json
  grafana/dashboards/internal/drive-details.json
  grafana/dashboards/internal/home.json
  grafana/dashboards/locations.json
  grafana/dashboards/mileage.json
  grafana/dashboards/overview.json
  grafana/dashboards/projected-range.json
  grafana/dashboards/reports/dutch-tax.json
  grafana/dashboards/states.json
  grafana/dashboards/statistics.json
  grafana/dashboards/timeline.json
  grafana/dashboards/trip.json
  grafana/dashboards/updates.json
  grafana/dashboards/vampire-drain.json
  grafana/dashboards/visited.json
  nix/module.nix
Labels: area:grafana

#4575 docs: enhance TeslaFi import documentation with updated Python script for bulk data export
  CHANGELOG.md
  website/docs/import/teslafi.md
Labels: kind:documentation

#4586 docs: add Entity Relationship Model section to development documentation
  CHANGELOG.md
  website/docs/development.md
  website/static/img/entity_relationship_model.png
Labels: kind:documentation
