Repository teslamate-org/teslamate, pull requests merged in 2025-07, with the labels that each got.

#4817 feat(mqtt): always publish healthy status and disable retain to prevent stale healthy status via mqtt
  CHANGELOG.md
  lib/teslamate/mqtt/pubsub/vehicle_subscriber.ex
  test/teslamate/mqtt/pubsub/vehicle_subscriber_test.exs
  test/teslamate/vehicles/vehicle_sync_test.exs
Labels: enhancement

#4764 feat: use the k8s-style API introduced in Grafana v12 if using manual dashboard setup
  CHANGELOG.md
  grafana/dashboards.sh
  grafana/dashboards/drives.json
  grafana/dashboards/overview.json
Labels: enhancement

#4819 doc: add OpenSSF scorecard
  CHANGELOG.md
  README.md
Labels: kind:documentation

#4833 sec(deps): override webpack-dev-server to version 5.2.1 to fix CVE-2025-30360
  CHANGELOG.md
  website/package-lock.json
  website/package.json
Labels: security

#4607 feat: enhance HTTP limits for managing fleets with over 10 vehicles
  CHANGELOG.md
  lib/teslamate/http.ex
  website/docs/configuration/environment_variables.md
Labels: enhancement, area:teslamate

#4677 feat: add duration time to charges details dashboard
  CHANGELOG.md
  grafana/dashboards/internal/charge-details.json
  website/static/screenshots/charging.png
Labels: enhancement, waiting for feedback, area:dashboard

#4798 feat: add total ascent & descent to the drive table, introduce slope-adjusted efficiency metric in drives dashboard
  CHANGELOG.md
  VERSION
  grafana/dashboards/drives.json
  lib/teslamate/log.ex
  lib/teslamate/log/drive.ex
  priv/repo/migrations/20250613133700_add_and_calculate_elevation_changes.exs
  test/teslamate/log/log_drive_test.exs
  website/static/screenshots/drives.png
Labels: enhancement, area:dashboard, area:teslamate

#4835 feat(nix): add idiomatic backup and restore scripts
  CHANGELOG.md
  nix/backup_and_restore.nix
  nix/module.nix
Labels: enhancement

#4829 docs: streamline installation guides
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  website/docs/advanced_guides/apache.md
  website/docs/advanced_guides/traefik.md
  website/docs/advanced_guides/unix_domain_sockets.md
  website/docs/configuration/api.md
  website/docs/development.md
  website/docs/installation/docker.md
  website/docs/installation/nixos.md
  website/docs/installation/unsupported/debian.md
  website/docs/installation/unsupported/freebsd.md
  website/docs/installation/unsupported/unraid.md
  website/docs/projects.md
  website/sidebars.js
Labels: kind:documentation

#4855 feat: use Grafana 12.1.0
  CHANGELOG.md
  grafana/Dockerfile
  grafana/dashboards/battery-health.json
  grafana/dashboards/charge-level.json
  grafana/dashboards/charges.json
  grafana/dashboards/charging-stats.json
  grafana/dashboards/database-info.json
  grafana/dashboards/drive-stats.json
  grafana/dashboards/drives.json
  grafana/dashboards/efficiency.json
  grafana/dashboards/internal/charge-details.json
  grafana/dashboards/internal/drive-details.json
  grafana/dashboards/internal/home.json
  grafana/dashboards/locations.json
  grafana/dashboards/mileage.json
  grafana/dashboards/overview.json
  grafana/dashboards/projected-range.json
  grafana/dashboards/reports/dutch-tax.json
  grafana/dashboards/states.json
  grafana/dashboards/statistics.json
  grafana/dashboards/timeline.json
  grafana/dashboards/trip.json
  grafana/dashboards/updates.json
  grafana/dashboards/vampire-drain.json
  grafana/dashboards/visited.json
Labels: area:grafana, docker
